name: Build Android APK

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v3

    # El ejecutable de gradle necesita permisos de ejecución en Linux
    - name: Make Gradle Wrapper Executable
      run: chmod +x android/gradlew

    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload Compiled APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk
